DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT EXISTS todos (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    content TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO todos (content) VALUES
('Task 1'),
('Task 2'),
('Task 3');
